### ISSUE TITLE
Create a filter feature that filters the list of search results

### ISSUE THREAD

**Issue by flurryjung** [srivassundar/politrack#18]
- [ ] ~~Filter by name~~

- [ ] ~~Filter by zipcode~~

- [x] Filter by party

- [x] Remove all filters
