### ISSUE TITLE
Create sorting feature to sort the list of search result

### ISSUE THREAD

**Issue by flurryjung** [srivassundar/politrack#20]
- [ ] ~~Sort by zipcode~~

- [x] Sort alphabetically by first name
- [x] Sort alphabetically by last name
- [x] Sort by relevance (default)
